#ifndef MBDATA_H
#define MBDATA_H
/* 
 * MODBUS REGISTER MAPPING FOR PROSYS PANEL
 * All data is mapped to 16 bit holding registers 4XXXX.
 */

#define WRITE_BYPASS_COMMAND_START_ADDRESS 0001
#define WRITE_UO_COMMAND_START_ADDRESS 0129
#define WRITE_PERMANENT_BYPASS_COMMAND_START_ADDRESS 0200
#define WRITE_ARM_COMMAND_START_ADDRESS 0618
#define WRITE_STAY_COMMAND_START_ADDRESS 0626
#define WRITE_DISARM_COMMAND_START_ADDRESS 0634

#define READ_SYSTEM_STATE_START_ADDRESS 1000
#define READ_ZONES_STATE_START_ADDRESS 1040
#define READ_TROUBLES_START_ADDRESS 1300
#define READ_UO_STATUS_START_ADDRESS 1600
#define READ_ZONE-PARTITION_TABLE_START_ADDRESS 1700
#define READ_STATUS_CHANGE_COUNTERS_START_ADDRESS 1830

#endif
